collector:
    termsDir: terms
    termsFileExtension: terms
    uptimeLogInterval: 60
    db_keys:
        collectorId: 'Collector'
        terms: terms
        currentTerm: currentTerm

mongo:
    connectionString: 'mongodb+srv://[hidden].pddgq.mongodb.net/GameTracker?retryWrites=true&w=majority'
    databaseName: 'GameTracker'

    collections:
        testingPrefix: 'Test_'
        games: 'Games'
        gamesMeta: 'Games_meta'
        collector: 'Collector'

    indexNames:
        games:
            text: "trackName_artistName_tags"
            deviceFamilies: "deviceFamilies"
            releaseDate: "releaseDate"
            currentVersionReleaseDate: "currentVersionReleaseDate"
            price: "price"
            popularity: "popularity"
            ratingCountCurrentVersion: "ratingCountCurrentVersion"
            metaRanking: "metaRanking"

gameValidator:
    updateInterval: 5
    lookupCount: 200

    db_keys:
        dateValidated: "dateValidated"

gamesMeta:
    db_keys:
        tags: 'tags'
        popularity_intervals: 'popularity_intervals'
        releaseYears: 'releaseYears'

mira:
    searchWaitInterval: 4
    searchURL_base: 'https://itunes.apple.com/search?term=__TERM__&entity=software,iPadSoftware&genreId=6014&limit=__LIMIT__&offset=__OFFSET__'
    limit: 200 # how many results to request in one api call
    minResults: 5 # if current search term returns less results than this number, then the next term in the list will be moved to
    minRatings: 0 # minimum amount of ratings app must have to be considered
    exhaustedSearchCount: 10 # if this many consecutive searches results in no new apps, then move to next term
    minChunkSizeForRigel: 30 # wait till Mira collects at least this many results before passing them to rigel

    api_keys:
        resultCount: 'resultCount'
        userRatingCount: 'userRatingCount'
        results: 'results'
        trackId: 'trackId'

    returnCodes:
        searchCompleted: 1

rigel:
    searchWaitInterval: 4
    lookupURL_base: 'https://uclient-api.itunes.apple.com/WebObjects/MZStorePlatform.woa/wa/lookup?version=2&id=__ID__&p=mdm-lockup&caller=MDM&platform=enterprisestore&cc=us&l=en'
    ignoreGenres: ['entertainment', 'games', 'gaming']

    api_keys:
        results: 'results'
        id: 'id' # this is the trackId in the lookupBlob
        hasInAppPurchases: 'hasInAppPurchases'
        userRating: 'userRating'
        ratingCount: 'ratingCount'
        genres: 'genres'
        genres_name: 'name'
        trackName: 'trackName'
        name: 'name'

    db_keys:
        tags: 'tags'
        metaRanking: 'metaRanking'
        searchBlob: 'searchBlob'
        lookupBlob: 'lookupBlob'
        ratingCount: "userRating.ratingCount" # child of lookupBlob
        ratingCountCurrentVersion: "userRating.ratingCountCurrentVersion" # child of lookupBlob
        ratingCurrentVersion: 'averageUserRatingForCurrentVersion' # child of searchBlob

    returnCodes:
        mongoWriteFail: 1
